# Generated by Django 5.2.1 on 2025-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
