# Generated by Django 5.2.1 on 2025-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
