# Generated by Django 5.2.1 on 2025-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_event_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='type',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
