# Generated by Django 5.2.1 on 2025-11-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_eventticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='type',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
