# Generated by Django 5.2.1 on 2025-05-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('p', 'Parent'), ('g', 'Graduate'), ('ge', 'Early Years Graduate'), ('ng', 'Student'), ('d', 'Plus One')], default='g', max_length=3),
        ),
    ]
