# Generated by Django 5.2.1 on 2025-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_email_order_email_address_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
