# Generated by Django 5.2.1 on 2025-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_email_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('p', 'Parent'), ('g', 'Graduate'), ('ge', 'Early Years Graduate'), ('ng', 'Learner'), ('d', 'Plus One')], default='g', max_length=3),
        ),
    ]
