# Generated by Django 5.2.1 on 2025-05-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('p', 'Parent'), ('g', 'Graduate'), ('ge', 'Early Years Graduate'), ('ng', 'Learner'), ('d', 'Plus One'), ('pk', 'Plus One (Child)')], default='g', max_length=3),
        ),
    ]
