# Generated by Django 5.2.1 on 2025-06-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['name']},
        ),
    ]
